# Generated by Django 5.2.8 on 2025-12-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='data_postagem',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
