# Generated by Django 5.2.8 on 2025-12-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_recreate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data_comentario',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
